title: Scramble JS Development Log
description: 2D combat flight simulator. By samid737.
show_downloads: true

baseurl: "/scrambledev" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://samid737.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty
logo: "/assets/images/PlayerDesert.png"
# social
author: "Dara Sami"
image: "/assets/images/PlayerDesert.png"

#  site:
#facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
#  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
google_analytics: "UA-107485622-2"

#plugins
plugins:
  - jekyll-seo-tag
